/*
   (c) Copyright 2009, Hewlett-Packard Development Company, LP

   See the file named COPYING for license details
*/

/** @file
    A module which uses the min/max index generated by dsextentindex to 
    pick out the appropriate extents. Unlike MinMaxIndex, maintains index 
    in memory, and only builds index on a single value.  
*/

#ifndef DATASERIES_SORTED_INDEX_MODULE_HPP
#define DATASERIES_SORTED_INDEX_MODULE_HPP

#include <boost/shared_ptr.hpp>

#include <DataSeries/GeneralField.hpp>
#include <DataSeries/IndexSourceModule.hpp>

/** SortedIndexModule assumes that for each file referenced by the
    index, that files rows are sorted on the index field. It is an error to
    violate this rule. */
class SortedIndexModule : public IndexSourceModule {
public:
    /** Create a new SortedIndexModule
	@param index_filename The file containing the index (created by 
	dsextent index)
	@param index_type The type of the extent indexed
	@param fieldname The name of the field to use as index
     */
    SortedIndexModule(const std::string &index_filename,
		      const std::string &index_type,
		      const std::string &fieldname);
    /** Destructor */
    virtual ~SortedIndexModule();

    /** Searches the index, subsequent calls to getExtent will result
	in only those extents that might contain the value being searched
	returned. Calling this before all the extents from a previous call
	to getExtent has returned NULL (i.e. all extents have been read) is
	an error.
     */
    void search(const GeneralValue &value);

    /** Searches the index for a set of values, subsequent calls to
        getExtent will result in all of the extents that may contain
        values within the search set, sorted by offset (to remove
        duplicates from the search process and hopefully improve read
        performance).
    */
    void searchSet(const std::vector<GeneralValue> &values);

    /** Searches the index for a range of values inclusive, subsequent
        calls to getExtent will result in all of the extents that may
        contain values within the search range.
    */
    void searchRange(const GeneralValue &start, const GeneralValue &end);

protected:
    virtual PrefetchExtent *lockedGetCompressedExtent();
    virtual void lockedResetModule();

private:
    // IndexEntry describes a single extent in the index
    struct IndexEntry {
	boost::shared_ptr<DataSeriesSource> source;
	GeneralValue minv;	// min value of index field in extent
	GeneralValue maxv;	// max value of index field in extent
	uint64_t offset;	// offset of extent in source
	IndexEntry(boost::shared_ptr<DataSeriesSource> source,
		   const GeneralValue &minv, const GeneralValue &maxv, 
		   uint64_t offset) 
	    : source(source), minv(minv), maxv(maxv), offset(offset) 
	{ }

	// Consider the following entry values for minv, maxv:
	// 
	// [ 1, 4 ]
	// [ 5, 7 ]
	// [ 7, 11 ]
	//
	// When we search for 7, we want to find the first extent
	// containing 7, which means that we have to compare based on
	// maxv rather than minv.
	bool operator<(const GeneralValue &rhs) const {
	    return maxv < rhs;
	}

	bool inRange(const GeneralValue &v) const {
	    return v >= minv && v <= maxv;
	}

        bool overlaps(const GeneralValue &min, const GeneralValue &max) const {
            return (maxv >= min && minv <= max);
        }
    };

    static bool entrySorter(const IndexEntry *lhs, const IndexEntry *rhs) {
        return lhs->source.get() < rhs->source.get() 
	    || (lhs->source.get() == rhs->source.get() && lhs->offset < rhs->offset);
    }

    static bool entryEqual(const IndexEntry *lhs, const IndexEntry *rhs) {
        return lhs->source.get() == rhs->source.get() && lhs->offset == rhs->offset;
    }

    typedef std::vector<IndexEntry> IndexEntryVector;

    bool need_reset; // need to reset the prefetch information
    size_t cur_extent; // current extent being processed, indexes into extents
    const std::string index_type;	// type of extent indexed
    std::vector<IndexEntryVector> index;// one index for each indexed file
    std::vector<IndexEntry *> extents;	// extents that contain searched value
};

#endif
